config/routes.rb
# File from Rails framework to configure the routes

Rails.application.routes.draw do
  resources :users
  resources :contacts
  resources :disciplines do
      resources :groups, shallow: true 
  end

  # You can have the root of your site routed with "root"
  root 'static_pages#home'

  match 'inscription/new/:user_id/:discipline_id' => 'inscriptions#create', :as => :inscription_create, via: :get


  get 'static_pages/about', as: 'about'
  get 'static_pages/home'
  get 'contacts/new'

  get '/dashboard' => 'disciplines#index', as: 'dashboard'

  get '/auth/github', as: 'github_login'
  get '/signin' => 'users#new', as: 'login'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/failure', to: 'sessions#failure'
end

app/models/discipline.rb
# File name :: discipline.rb
# Description :: Class Discipline is a model class
# to represent discipline, a users group created by admins

class Discipline < ActiveRecord::Base
  has_many :inscriptions
  has_many :groups
  belongs_to :user

  # Method responsible for finding all disciplines that the user searched, in the DB.
  def self.search(query)
    where('discipline_name like ?', "%#{query}%")
  end

  # Method to verificate if the user exist in database
  def is_registered?
    @is_registered = false
    @inscriptions = Inscription.where(discipline_id: id)

    for inscription in @inscriptions
      @is_registered = true if inscription.discipline_id == id
    end

    @is_registered
  end

  # Method to return all users registered
  def users_registered
    @inscriptions = Inscription.where(discipline_id: id)
    @list_of_users_registred = []

    for inscription in @inscriptions
      if inscription.discipline_id == id
        @list_of_users_registred << inscription.user_id
      end
    end
    @list_of_users_registred
  end
end

app/controllers/disciplines_controller.rb
# File name :: disciplines_controller.rb
# Description :: Class DiscilplinesController is a controller
# to take actions for all disciplines.

class DisciplinesController < ApplicationController
  # Default methods for DisciplinesController

  # The method index will show all the disciplines the user has, but if a search
  # has been done, it will show the results for the search
  def index
    
    if params[:search]
      @disciplines = Discipline.search(params[:search])
      logger.debug "Recieve a discipline of user owner #{@discipline}"

      @page_title = 'Resultado da Busca'
      @disciplines_not_found = 'Nenhuma disciplina encontrada...'

    else
      @disciplines = make_disciplines

      @page_title = 'Minhas Disciplinas'
      @disciplines_not_found = "Você não possui nenhuma disciplina, clique no
     botão abaixo para criar uma ou pesquise disciplinas para se inscrever."
    end
  end

  # The method show is to show one of disciplines with details
  def show
    @discipline = Discipline.find(params[:id])

    @owner = User.find(@discipline.user)

    @participants = make_participants
    @groups = Group.where("discipline_id = ?", @discipline.id)

    if params[:search]
      @groups = @groups.search(params[:search])
      logger.debug "Recieve a group of user owner #{@group}"

      @page_title = 'Resultado da Busca'
      @groups_not_found = 'Nenhum grupo encontrado...'
    else  
      @page_title = "Grupos da disciplina #{@discipline.discipline_name}"
      @groups_not_found = "Não existe nenhum Grupo criado, clique no
     botão abaixo para criar um."
    end
  end

  # Instantiate a new discipline
  def new
    @discipline = current_user.disciplines.build
  end

  # Set new params into discipline
  def edit
    @discipline = current_user.disciplines.find(params[:id])
  end

  # Save the new discipline with validates
  def create
    @discipline = current_user.disciplines.build(discipline_params)
    logger.debug "Recieve a discipline of user owner #{@discipline}"

    if @discipline.save
      redirect_to @discipline, notice: 'Nova disciplina criada'
    else
      render action: 'new'
    end
  end

  # Update the discipline edited into database
  def update
    @discipline = current_user.disciplines.build(discipline_params)

    if @discipline.update(room_params)
      redirect_to @discipline, notice: 'Você atualizou uma disciplina'
    else
      render action: 'edit'
    end
  end

  # Method to remove a discipline instance
  def destroy
    @discipline = current_user.disciplines.find(params[:id])
    @discipline.destroy

    redirect_to disciplines_url
  end

  # Method to associate a new instance into the current user
  def make_disciplines
    @disciplines_from_user = registered_disciplines(current_user)
    logger.debug "Recieve a list of discipline_id #{@disciplinesFromUser.is_a?(Array)}"
    @disciplines_registered = []

    for discipline_id in @disciplines_from_user
      @get_disciplines = Discipline.find(discipline_id)
      @disciplines_registered << @get_disciplines
    end

    @disciplines_registered
  end

  # Method to insert a new user to the discipline
  # this user will be participant role
  def make_participants
    @participants_id = @discipline.users_registered
    logger.debug "Recieve a list of discipline_id: #{@participantsId.is_a?(Array)}"
    @participants = []

    for user_in_discipline_id in @participants_id
      @get_user_in_discipline = User.find(user_in_discipline_id)
      @participants << @get_user_in_discipline
    end

    @participants
  end

  def registered_disciplines(user)
    @inscriptions = Inscription.where(user_id: user.id)
    @list_of_discipline_registred = []

    @inscriptions.each do |inscription|
        @list_of_discipline_registred.push(inscription.discipline_id)
    end

    current_user.disciplines.each do |discipline|
       @list_of_discipline_registred.push(discipline.id)
    end

    @list_of_discipline_registred
  end

  # Definning the Class params
  # @params discipline_name => Name of the discipline
  #         discipline_description => Some things about the discipline

  private

  def discipline_params
    params
      .require(:discipline)
      .permit(:discipline_name, :discipline_description)
  end
end

app/helpers/disciplines_helper.rb
# File name :: disciplines_helper.rb
# Description :: Class DisciplinesHelper from Rails framework
# to configure disciplines setups and tools

module DisciplinesHelper
  def belongs_to_user(_discipline)
    current_user && room.user == current_user
  end
end

app/views/disciplines/_details.html.erb
<a data-parent="#accordion" data-toggle="collapse" href="#description">Descrição
</a>
<table class="table" id="description">
  <tbody>
    <tr>
      <td>
        <p>
          <%= @discipline.discipline_description%>
        </p>
      </td>
    </tr>
  </tbody>
</table>

<a data-parent="#accordion" data-toggle="collapse" href="#people">Pessoas</a>

<table class="table" id="people">
  <tbody>
    <tr>
      <td>
        <b>
          <p>Criador:
          </b>
          <%= @owner.username%>
        </p>

        <b>
          <p>Participantes:
          </b>
        </p>

        <% @participants.each do |participant|%>
        <p><%= participant.username %>
        </p>

        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
  $("#description").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });

    $("#people").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
</script>

<% if current_user.id != @owner.id && @discipline.is_registered? == false %>
<%= link_to 'Inscreva-se', :controller => 'inscriptions', :action => 'create', :user_id=>"#{current_user.id}", :discipline_id=>"#{@discipline.id}", :class=>"btn btn-primary btn-sm"%>
<% end %>
<% if current_user.id == @owner.id %>
<%= link_to 'Excluir', @discipline, method: :delete, data: { confirm: 'Tem certeza que deseja excluir essa disciplina?' }, class: "btn btn-danger btn-xs", style: "color:white; text-decoration:none;" %>
<% end %>

app/views/disciplines/index.html.erb
<!--
  File name: index.html.erb
  Description: This file contains what will show independent the page to represent all disciplines
-->
<!DOCTYPE html>
<html lang="en">
  <body style="padding-top: 6%; padding-left:2%;">

    <div class="row">
     
        <div class="input-group" style ="width:70%;padding-left:30%;">
          <center>
          <%= form_tag(disciplines_path, :method => :get) do %>
          <%= text_field_tag 'search',nil, placeholder: 'Procure por disciplinas...', :class => "form-control" %>
        </center>
          <span class="input-group-btn">
            <%= submit_tag "Buscar", :class => "btn btn-default" %>
          </span>
          <% end %>

        </div>
        <!-- /input-group -->
 
      <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
    <div class="disciplines-layout">
      <div class="row">
        <h3><%= @page_title %></h3>
      </div>
      <% if @disciplines.empty? %>
      <div class="row">
        <div class="col-lg-6">
          <div class="alert alert-info" role="alert" style="width:750px;">
            <%= @disciplines_not_found %>
          </div>
        </div>
      </div>
      <%else%>
      <div class="row">
        <%@disciplines.each do |discipline|%>
        <div class="col-sm-4 col-md-3">
          <div class="thumbnail">
            <%=image_tag("disciplinas_image.png", style: 'padding-top: 0%; padding-left: 0%; height: 40px;')%>
            <div class="caption">
              <h3 style="text-align:center"><%= discipline.discipline_name%></h3>
              <p><%= discipline.discipline_description %></p>
              <% if current_user.id == discipline.user.id%>
              <p style="color:red;"> (dono) </p>
              <% end %>
              <%= link_to "Entrar", discipline_path(discipline), :class => "btn btn-default" %>
            </div>
          </div>
        </div>
        <%end%>
      </div>
      <%end%>
      <p>
        <a class="btn btn-primary btn-lg" href="/disciplines/new" role="button">Criar uma disciplina</a>
      </p>
    </div>
  </body>
</html>

app/views/disciplines/new.html.erb
<!--
  File name: application.html.erb
  Description: This file contains what will show independent the page to create a new discipline
-->
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="disciplines-layout">
      <h3>Crie uma nova disciplina</h3>

      <%= bootstrap_form_for @discipline do |f|%>
      <p>
        <%= f.text_field :discipline_name, width: "10px", label: "Nome",required: true %>
      </p>
      <p>
        <%= f.text_area :discipline_description, label: "Descrição" %>
      </p>

      <%= f.submit "Criar Drisciplina", class: "btn btn-primary" %>

      <%end%>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../assets/stylesheets/bootstrap.min.js"></script>
  </body>
</html>

app/views/disciplines/show.html.erb
<!--
File name: show.html.erb
Description: This file contains what will show independent the page show a specific discipline.
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Gitting:
    <%= @discipline.discipline_name%></title>
  </head>
  <body style = "paddin-top=-1%; color:gray;">
    <div id="wrapper">
      <!-- Sidebar -->
      <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
          <li class="sidebar-brand">
            <a href="#">
              <%= @discipline.discipline_name%>
            </a>
          </li>
          <li>
            <%= render :partial => 'disciplines/details' %>
          </li>
        </ul>
      </div>

      <!-- /#sidebar-wrapper -->
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <p class="btn btn-primary" href="#menu-toggle" id="menu-toggle"><< | >></p>
              <div class="container-discipline">
                <%= render :file => 'groups/index' %>
                <br>
                <% if current_user.id == @owner.id || @discipline.is_registered? == true %>
                <%= link_to raw("<i class=\"fa fa-users\"> Criar um grupo </i>"),
                      new_discipline_group_path(@discipline), class: "btn btn-primary  btn-small"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
      $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
        });
    </script>
  </body>
  </html>