config/routes.rb
# File from Rails framework to configure the routes

Rails.application.routes.draw do
  resources :users
  resources :contacts
  resources :disciplines do
      resources :groups, shallow: true 
  end

  # You can have the root of your site routed with "root"
  root 'static_pages#home'

  match 'inscription/new/:user_id/:discipline_id' => 'inscriptions#create', :as => :inscription_create, via: :get


  get 'static_pages/about', as: 'about'
  get 'static_pages/home'
  get 'contacts/new'

  get '/dashboard' => 'disciplines#index', as: 'dashboard'

  get '/auth/github', as: 'github_login'
  get '/signin' => 'users#new', as: 'login'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/failure', to: 'sessions#failure'
end

app/models/inscription.rb
# File name :: contact.rb
# Description :: Class Contact is a model class
# to represent users that will contact the team

class Inscription < ActiveRecord::Base
  belongs_to :users
  belongs_to :disciplines
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
  before_action :set_inscription, only: [:show, :edit, :update, :destroy]

  # GET /inscriptions
  # GET /inscriptions.json
  def index
    @inscriptions = Inscription.all
  end

  # GET /inscriptions/1
  # GET /inscriptions/1.json
  def show
  end

  # GET /inscriptions/new
  def new
    @inscription = Inscription.new
  end

  # GET /inscriptions/1/edit
  def edit
  end

  # POST /inscriptions
  # POST /inscriptions.json
  def create
    @inscription = Inscription.new(inscription_params)

    respond_to do |format|
      if @inscription.save
        format.html { redirect_to disciplines_path, notice: 'Inscription was successfully created.' }
        format.json { render :show, status: :created, location: @inscription }
      else
        format.html { render :new }
        format.json { render json: @inscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inscriptions/1
  # PATCH/PUT /inscriptions/1.json
  def update
    respond_to do |format|
      if @inscription.update(inscription_params)
        format.html { redirect_to @inscription, notice: 'Inscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @inscription }
      else
        format.html { render :edit }
        format.json { render json: @inscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inscriptions/1
  # DELETE /inscriptions/1.json
  def destroy
    @inscription.destroy
    respond_to do |format|
      format.html { redirect_to inscriptions_url, notice: 'Inscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inscription
      @inscription = Inscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inscription_params
      params
      .permit(:user_id, :discipline_id)
    end
end

app/helpers/inscriptions_helper.rb
module InscriptionsHelper
end

app/views/inscriptions/_form.html.erb
<%= simple_form_for(@inscription) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/inscriptions/edit.html.erb
<h1>Editing Inscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @inscription %> |
<%= link_to 'Back', inscriptions_path %>

app/views/inscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inscriptions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inscriptions.each do |inscription| %>
      <tr>
        <td><%= link_to 'Show', inscription %></td>
        <td><%= link_to 'Edit', edit_inscription_path(inscription) %></td>
        <td><%= link_to 'Destroy', inscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inscription', new_inscription_path %>

app/views/inscriptions/new.html.erb
<h1>New Inscription</h1>

<%= render 'form' %>

<%= link_to 'Back', inscriptions_path %>

app/views/inscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inscription_path(@inscription) %> |
<%= link_to 'Back', inscriptions_path %>